### ISSUE TITLE
Update the WordPress SVN repo?

### ISSUE THREAD

**Issue by kyle-jennings** [curtismchale/post-tags-and-categories-for-pages#10]
hey @curtismchale, I noticed this plugin hasn't been updated on the WordPress repos in 3 years.. but it looks like you've put some work into it and tested up to 4.5?

I haven't taken a look at the code yet, but if it fixes things like [this](https://wordpress.org/support/topic/fyi-please-consider-updating-your-code-2/) then I know lots of people would love to see an update

**Comment by curtismchale** [comment]
It fixes some things.

I honestly almost never use SVN so the hurdle is always me trying to figure out how to push any changes to SVN again. Every time I need to I have to learn how again.

**Comment by curtismchale** [comment]
Done.
