### ISSUE TITLE
Update wordpress.org repository?

### ISSUE THREAD

**Issue by macbookandrew** [curtismchale/Post-Tags-and-Categories-for-Pages#9]
Curtis,

Any chance you could update the Wordpress.org plugin repo with the changes? It’s saying the plugin hasn’t been updated in 2+ years 😄

**Comment by curtismchale** [comment]
It's on my list, but we had a new baby last week and I hate SVN. It will get done at some point.

**Comment by macbookandrew** [comment]
Congratulations!

[This deploy script](https://github.com/GaryJones/wordpress-plugin-git-flow-svn-deploy) has helped me out tremendously. Not sure how well it would work for something already set up using SVN, but might be worth looking at when you get around to it.
